### PR TITLE
chore(deps): update pgx to 5.11.0 with pgxmock v5

### PR DESCRIPTION
**Pull request by is7Qin**
## Why

`#15` bumps `github.com/jackc/pgx/v5` to 5.11.0, but pgx 5.11.0 adds `TypeMap`
to the `pgx.Rows` interface, which the pinned `pgxmock v4.9.0` (its final v4
release) does not implement. That breaks the test build, so #15 cannot be
merged green on its own.

## What

- Bump `github.com/jackc/pgx/v5` 5.10.0 -> 5.11.0 (the intent of #15).
- Migrate the three test files using pgxmock from `v4` to `v5`; v5 targets
  pgx 5.11.0, so no test expectations change.

## Verification

Local run mirroring CI (`go vet ./...`, `go build ./...`,
`go test -count=1 -p 1 ./...` against a real PostgreSQL 18 test database, plus
`go generate` drift check on the handler/ent code): all green, no drift.

Supersedes #15.

### CODE REVIEW

**Comment by is7Qin** [comment]
I have read the CLA Document and I hereby sign the CLA
